title: Chunyin Li's Homepage
page-top-title: Chunyin Li
top-section-bg-text: Human-Computer Interaction
home-subtitle: Chunyin(Junxian) Li&ensp;|&ensp;李俊贤
copyright-text: '&copy; Chunyin Li 2024-2025. All Rights Reserved.'
