title: Chun Yin LI's Homepage
page-top-title: Chun Yin LI
top-section-bg-text: Human-Computer Interaction
home-subtitle: Chun Yin (Junxian) LI&ensp;|&ensp;李俊贤
copyright-text: '&copy; Chun Yin LI 2024-2025. All Rights Reserved.'
