title: Junxian Li's Homepage
page-top-title: Junxian Li
top-section-bg-text: Human-Computer Interaction
home-subtitle: Junxian Li&ensp;|&ensp;李俊贤
copyright-text: '&copy; Junxian Li 2024-2025. All Rights Reserved.'
